# Site settings
title: Tim Cartwright - Web Developer
email: tim@websitesbytim.com
description: > # Tim Cartwright is a freelance, full stack web developer
baseurl: "/portfolio-b/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  timcartwright
permalink: :categories/:title

# Build settings
markdown: kramdown
